# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package
run-name: ${{ github.actor }} is push the code... deploying it...

on:
  push: 
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: install dependencies
      - run: npm install -force
      - run: cd client && install -force
      - run: cd server && install -force

      - name: run both client and backend
      - run: npm run start:both 

