name: Backend tests
run-name: ${{ github.actor }} is testing
on: [push]
jobs:
  run-backend-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: cd client
      - run: npm install
      - run: npm test