name: Frontend Tests
run-name: ${{ github.actor }} is testing the front
on: [push]

jobs:
  run-frontend-tests:
    runs-on: ubuntu-latest
    defaults:
        run:
            working-directory: ./client
    steps:
    - uses: actions/checkout@v2
    - name: Run Cypress Tests
      uses: cypress-io/github-action@v4
      with:
        command: npx cypress run
        browser: chrome