name: Frontend Tests
run-name: ${{ github.actor }} is testing the backend
on: [push]

jobs:
  run-frontend-tests:
    runs-on: ubuntu-latest
    defaults:
        run:
            working-directory: ./client
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14  # Use the desired Node.js version
    - run: |
        cd client  # Change to the "client" directory
        npm install

    - name: Run Cypress Tests
      run: |
        cd client  # Change to the "client" directory
        npm run cypress:open  # Adjust the script name to your Cypress test script
