name: Frontend tests
run-name: ${{ github.actor }} is testing the frontend
on: [push]
jobs:
  run-frontend-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          command: npx cypress run
          browser: chrome
