name: Frontend Tests
run-name: ${{ github.actor }} is testing the front
on: [push]

jobs:
  run-frontend-tests:
    runs-on: ubuntu-latest
    defaults:
        run:
            working-directory: ./client
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14  # Use the desired Node.js version
    - name: Instal dependencies
      run: 
        npm install

    - name: Run Cypress Tests
      run: |
        npx cypress run  # Adjust the script name to your Cypress test script
        


